releases:   
  - name: "kibana"
    namespace: "elastic"
    labels:
      default: true
      component: kibana
      role: elastic
    chart: "../helm/charts/kibana"
    wait: true
    timeout: 600
    installed: {{ env "KIBANA_INSTALLED" | default "true" }}
    values:
    - elasticsearchHosts: "https://elasticsearch-data:9200"
      image: "amazon/opendistro-for-elasticsearch-kibana"
      imageTag: "1.3.0"
      resources:
        requests:
          cpu: "100m"
          memory: "7Gi"
        limits:
          cpu: "1000m"
          memory: "8Gi"
      kibanaConfig:
        kibana.yml: |
          elasticsearch.ssl.verificationMode: none
          elasticsearch.username: kibanaserver
          elasticsearch.password: kibanaserver
          elasticsearch.requestHeadersWhitelist: ["securitytenant","Authorization"]          
          opendistro_security.multitenancy.enabled: true
          opendistro_security.multitenancy.tenants.preferred: ["Private", "Global"]
      extraEnvs: 
        - name: ELASTIC_USERNAME
          value: admin
        - name: ELASTIC_PASSWORD
          value: admin
