# Default values for cluster-config
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
cloudProviders:
  aws:
    zones:
    - us-west-2a
    - us-west-2b
    - us-west-2c
