# Default values for cluster-config
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
cloudProviders:
  aws:
    zones:
    - ap-southeast-1a
    - ap-southeast-1b
    - ap-southeast-1c
